{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle",
    "module": "Boxlib-forge",
    "version": "9.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Boxlib-forge-9.0.0.jar",
          "url": "Boxlib-forge-9.0.0.jar",
          "size": 200952,
          "sha512": "48a1586d57ba6e9ef8191785e054248197fc8576e9a278348f552339d75967aa6a1eee8f81bc41f56e19c1acd6a6484e972f704dfb8fe5f2ca9573abc8b9b6d7",
          "sha256": "8603be35ee2ec660eee7b4d39efd4364577f101d0e5606c27ce9992d3f26163d",
          "sha1": "3a20c5ad3c3a81ddd83efcf54a09dd57bed0872e",
          "md5": "ab53eeba9cd8dfd9522f6c41837a51e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Boxlib-forge-9.0.0.jar",
          "url": "Boxlib-forge-9.0.0.jar",
          "size": 200952,
          "sha512": "48a1586d57ba6e9ef8191785e054248197fc8576e9a278348f552339d75967aa6a1eee8f81bc41f56e19c1acd6a6484e972f704dfb8fe5f2ca9573abc8b9b6d7",
          "sha256": "8603be35ee2ec660eee7b4d39efd4364577f101d0e5606c27ce9992d3f26163d",
          "sha1": "3a20c5ad3c3a81ddd83efcf54a09dd57bed0872e",
          "md5": "ab53eeba9cd8dfd9522f6c41837a51e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Boxlib-forge-9.0.0-sources.jar",
          "url": "Boxlib-forge-9.0.0-sources.jar",
          "size": 137850,
          "sha512": "a0f7765f19bef0f30c728a93184a1b5cad0fcf418dbbd39b4b69d6d667bf66994ac7447060808a9c3dd94a94c2dbc5c017237d762eaf66b96d59be445c8cb3f2",
          "sha256": "c7f1a027c9c4aee47189d9f4a7fe89c85f11a8659e9df549ae6b2b8daeae1b54",
          "sha1": "2db51ccff2f257681200375a76f9c009fbf6b6d8",
          "md5": "755f0c09c0031ee2494b2625efae6a28"
        }
      ]
    }
  ]
}
