{
  "formatVersion": "1.1",
  "component": {
    "group": "me.boxadactle",
    "module": "BoxLib-Fabric",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BoxLib-Fabric-4.3.0.jar",
          "url": "BoxLib-Fabric-4.3.0.jar",
          "size": 120663,
          "sha512": "d41d8ceddef025e4dc5a37994c710fd94d5140c84fb87cd2832183d4c45f995908089c14346c06aa7cee108316090d4fb7058f877c9f8cc82d11ee98d7abd163",
          "sha256": "a4866aca9874fafc1e6c9b0d6bbdc9528ec637b063c4aa4211e0178062298dfa",
          "sha1": "a97bbc4461088394644a1afcdc71e39ea8ebfee6",
          "md5": "28b485c465cbe6b5b14b9ffaef2f09f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.85.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-Fabric-4.3.0.jar",
          "url": "BoxLib-Fabric-4.3.0.jar",
          "size": 120663,
          "sha512": "d41d8ceddef025e4dc5a37994c710fd94d5140c84fb87cd2832183d4c45f995908089c14346c06aa7cee108316090d4fb7058f877c9f8cc82d11ee98d7abd163",
          "sha256": "a4866aca9874fafc1e6c9b0d6bbdc9528ec637b063c4aa4211e0178062298dfa",
          "sha1": "a97bbc4461088394644a1afcdc71e39ea8ebfee6",
          "md5": "28b485c465cbe6b5b14b9ffaef2f09f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-Fabric-4.3.0-sources.jar",
          "url": "BoxLib-Fabric-4.3.0-sources.jar",
          "size": 76779,
          "sha512": "ec2be9b7cb3a2301bf28f7c9053a281959ebb4a8d7d0478b4e5bd62a2e8511a4cde6891141893e5e41c219dbb897918bb07b9b87bbbd750f9402ebbfefd8c157",
          "sha256": "95ed56cdd35ae3ff62b3220278046aa4886514bfc7c76269aab8b72d5457d9ad",
          "sha1": "5a095bdc9737c027ea1b23113398dd32c1886340",
          "md5": "f8ea58b9b508c4d0cffffe55435d3a24"
        }
      ]
    }
  ]
}
