{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib",
    "version": "5.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BoxLib-5.4.2.jar",
          "url": "BoxLib-5.4.2.jar",
          "size": 155931,
          "sha512": "f69261da7a78fea9a8c21c9381de3f084b3ad3e21c68830c91539432ca187ad3ed71d8da4e9809f3c3d4225723b05adf84f47680531efd4bd572132482e14372",
          "sha256": "bd0245bbd7feb6246e95bfce446209701ffa1e8caf0514bef1a684d8a5cab07d",
          "sha1": "dfbec1330629f0b6e740502ebf99f9eb8f85ef26",
          "md5": "92d1479f90d9e2bb365ec0bc52c93360"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-5.4.2.jar",
          "url": "BoxLib-5.4.2.jar",
          "size": 155931,
          "sha512": "f69261da7a78fea9a8c21c9381de3f084b3ad3e21c68830c91539432ca187ad3ed71d8da4e9809f3c3d4225723b05adf84f47680531efd4bd572132482e14372",
          "sha256": "bd0245bbd7feb6246e95bfce446209701ffa1e8caf0514bef1a684d8a5cab07d",
          "sha1": "dfbec1330629f0b6e740502ebf99f9eb8f85ef26",
          "md5": "92d1479f90d9e2bb365ec0bc52c93360"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-5.4.2-sources.jar",
          "url": "BoxLib-5.4.2-sources.jar",
          "size": 41371,
          "sha512": "5321d57cc666c9c1a07cf27422f8ec17a9a45c253a9f62994b6d9431e283b09eec9b174762ce418c4fa3273bf77bd6d6283a37010db821ec525bfc19d00f0a93",
          "sha256": "130cf27a5ceecbdf42c5657da071061c012cc842c5263b208d5b67d09c50584e",
          "sha1": "42ad7ae3299884199fd305392cc01863b4b8ced3",
          "md5": "c31e8417448f361869f3f39f6aa53b64"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-5.4.2-shadow.jar",
          "url": "BoxLib-5.4.2-shadow.jar",
          "size": 150685,
          "sha512": "8b2cca41c25761c15af0c06ecca1eff3e5980b901fafa209144ac3919b7f2458534d4234b507eb09ec7140d504db6de254e4f114a448a7630d89780e11ea6046",
          "sha256": "64dcff9ae66958b7cc1e36dc173a003622f622a8b7dc5c0298cca3214f3a808b",
          "sha1": "fa73d8bdadda3319094602a8e508290f886ebf55",
          "md5": "6aa6c2b8a953cb5e555905e1d6b78b94"
        }
      ]
    }
  ]
}
