{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle",
    "module": "Boxlib",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Boxlib-6.0.0.jar",
          "url": "Boxlib-6.0.0.jar",
          "size": 190018,
          "sha512": "3a5367b776c7369da0d982fc3c5d3a6abc93fb5ec004cb42cb0a8f256fe79260ec483b06899d9adf2fe6c93a3bf5b0dc93119991ec5b4b7086b4bef637a74c14",
          "sha256": "11aacb4aff4e4e3bc818a8407abf7132f10c0a831dc554e0550578b8dc6c8985",
          "sha1": "6752df5d9ddceb83632012afb8a2211609d27c7e",
          "md5": "b090f76fb0d0a1dfe6fa90e036e77744"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        }
      ],
      "files": [
        {
          "name": "Boxlib-6.0.0.jar",
          "url": "Boxlib-6.0.0.jar",
          "size": 190018,
          "sha512": "3a5367b776c7369da0d982fc3c5d3a6abc93fb5ec004cb42cb0a8f256fe79260ec483b06899d9adf2fe6c93a3bf5b0dc93119991ec5b4b7086b4bef637a74c14",
          "sha256": "11aacb4aff4e4e3bc818a8407abf7132f10c0a831dc554e0550578b8dc6c8985",
          "sha1": "6752df5d9ddceb83632012afb8a2211609d27c7e",
          "md5": "b090f76fb0d0a1dfe6fa90e036e77744"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Boxlib-6.0.0-sources.jar",
          "url": "Boxlib-6.0.0-sources.jar",
          "size": 132472,
          "sha512": "ae5c31375504c0f146523661db418d98233dbb0a70190bd0977229c1553ccc76eb3e9b8f9b0b9549d553507f8940c06c13e44c0b10774d8e1574e098e5da32be",
          "sha256": "9ede09a5887e23be54632359fbf19f4f0dd4f64fbed7c449b40d8ff98834f295",
          "sha1": "5d1e89f952a05d4a76703e7c4e6cb66d92e303b5",
          "md5": "645632e2c6414058857da46a406e6128"
        }
      ]
    }
  ]
}
