{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib-forge",
    "version": "5.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BoxLib-forge-5.4.2.jar",
          "url": "BoxLib-forge-5.4.2.jar",
          "size": 210726,
          "sha512": "9d574ef3c2005b00c4936f68e717840e7ea3b76a8c69537f26629bb876eaa973c78b1792f5ba7e5303f85f6b7b080dc93677e86e5cb49bc5c13108d6bac6ed07",
          "sha256": "a44089bbe46061f8a66404f9d3c0094ecc0d198ab124ae93947b0b02bc8ffbad",
          "sha1": "fc8b6a3fcf204f681564eb58f772fd59e414f287",
          "md5": "166c491eab1447b687419787e037b5e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-forge-5.4.2.jar",
          "url": "BoxLib-forge-5.4.2.jar",
          "size": 210726,
          "sha512": "9d574ef3c2005b00c4936f68e717840e7ea3b76a8c69537f26629bb876eaa973c78b1792f5ba7e5303f85f6b7b080dc93677e86e5cb49bc5c13108d6bac6ed07",
          "sha256": "a44089bbe46061f8a66404f9d3c0094ecc0d198ab124ae93947b0b02bc8ffbad",
          "sha1": "fc8b6a3fcf204f681564eb58f772fd59e414f287",
          "md5": "166c491eab1447b687419787e037b5e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-forge-5.4.2-sources.jar",
          "url": "BoxLib-forge-5.4.2-sources.jar",
          "size": 82325,
          "sha512": "d32145c7997549f136151f83154bcc97be0d57824f572e06566a9528b7ec5f8c06f60c79bd0a119b89038bd732616191dc205e33ec9687998576afde2ffeb469",
          "sha256": "adc22cc9c18951ea60835fda818e840cb6378371a013a06f984e40a164c600a8",
          "sha1": "f7ca2f3563520148dd1f05585e5fdfe10540c320",
          "md5": "7d4ee3dd697ce885316d4b0409ff1528"
        }
      ]
    }
  ]
}
