{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib",
    "version": "5.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BoxLib-5.3.4.jar",
          "url": "BoxLib-5.3.4.jar",
          "size": 143826,
          "sha512": "fe21f1ed412d1553d07d0b5e3b77a09aa33b797f060aa709ffbbe999a5bc946d5337461110572ebc2abf03eb1fce3ea5d601a5dfe4904fc5e8eebcc57d3b462b",
          "sha256": "e365265d1e4f9539cb78bc3996a952727c605a566bbae070befd8b91ebf4581b",
          "sha1": "2de7ee919f6b435eb2bb75affeef6deab2f816f7",
          "md5": "8c2ba3ee72a956e09496d94e8e752170"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-5.3.4.jar",
          "url": "BoxLib-5.3.4.jar",
          "size": 143826,
          "sha512": "fe21f1ed412d1553d07d0b5e3b77a09aa33b797f060aa709ffbbe999a5bc946d5337461110572ebc2abf03eb1fce3ea5d601a5dfe4904fc5e8eebcc57d3b462b",
          "sha256": "e365265d1e4f9539cb78bc3996a952727c605a566bbae070befd8b91ebf4581b",
          "sha1": "2de7ee919f6b435eb2bb75affeef6deab2f816f7",
          "md5": "8c2ba3ee72a956e09496d94e8e752170"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-5.3.4-sources.jar",
          "url": "BoxLib-5.3.4-sources.jar",
          "size": 40979,
          "sha512": "5e79c8c38072e9f111a74917a68a1cdcc6f876e063f93e6e517bee9daad605b8d7a89740c9d00ee0692a0d9387290f70c80b4356136ffe6e6ab833d65d775c0f",
          "sha256": "d136b1b31f4d16026e7b15dcc935d3ca2be85b681e6bd0e2a5507fb38d60f52e",
          "sha1": "8a1965c8c3c0598a8ca12c125f1ee565cc465049",
          "md5": "9b9441f3225042f07657c45197ecd041"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-5.3.4-shadow.jar",
          "url": "BoxLib-5.3.4-shadow.jar",
          "size": 138864,
          "sha512": "5964160157a008b8f274b25adb2d0b2404fda715311644d9d190a014438311a2e4342e4ad6c5083c34cf7b7fecafc81c816c90bbab25e9b1d9bdeb3fae864b3a",
          "sha256": "5200248355be3e8edda3495ec51f197b1065b9d8879375995b00ceb5bb09a670",
          "sha1": "2f93d8d6ffef52dec01ab59c43d05784d5951661",
          "md5": "9da3242f602b51b5815bf424223497c9"
        }
      ]
    }
  ]
}
