{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BoxLib-5.4.1.jar",
          "url": "BoxLib-5.4.1.jar",
          "size": 155931,
          "sha512": "7302efab149b1834679855e14581e3239cedeb615386ff1fbcfc3e1cfef228493d30192cdfa7c6bf5b78a91fd94c4fa85b399ce692f464178c9bbcd339bd0049",
          "sha256": "0321af6f2699ab91d3295b7276ea532db7c9b4b9cee250b3c5ab3a704a522968",
          "sha1": "efd3a6a1a4243c6f90d18fd98cfc70a352a15a2c",
          "md5": "757bd2f1483bb3e6beaf9d60a3783a60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-5.4.1.jar",
          "url": "BoxLib-5.4.1.jar",
          "size": 155931,
          "sha512": "7302efab149b1834679855e14581e3239cedeb615386ff1fbcfc3e1cfef228493d30192cdfa7c6bf5b78a91fd94c4fa85b399ce692f464178c9bbcd339bd0049",
          "sha256": "0321af6f2699ab91d3295b7276ea532db7c9b4b9cee250b3c5ab3a704a522968",
          "sha1": "efd3a6a1a4243c6f90d18fd98cfc70a352a15a2c",
          "md5": "757bd2f1483bb3e6beaf9d60a3783a60"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-5.4.1-sources.jar",
          "url": "BoxLib-5.4.1-sources.jar",
          "size": 41371,
          "sha512": "4ef0ad5e3e7e3883d7f07528bd5f391db13eb389ca8ccd203964f3045f81d04348036a161b1ef70b4e999ba27200c201c2b6313c961695e6e4f5aa534c280191",
          "sha256": "e4935fa10d37a46ced33691836c164ca586cce577fd62a084fee9307bf0b53da",
          "sha1": "f23717339aa054fb84ec9d4f940f971166b65e2b",
          "md5": "9ed89c31a80439da088cee613cd8c34e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-5.4.1-shadow.jar",
          "url": "BoxLib-5.4.1-shadow.jar",
          "size": 150685,
          "sha512": "578eaeda334f69efc1ea587198f4c6b0061842f309e3f731360ec0f7e51edea87a3ddcc5bee3d6748ea04de0f9c549848dbed20a66848f0ea8988b5f6ffc8cd9",
          "sha256": "6b60e93b223235673295186fa59e80b577b045c0bf42333be2db54062660bc83",
          "sha1": "1e4cd263b0be646c8c4377dd421cecf3246663db",
          "md5": "7ade7822ce0d753135875b15f7559b5e"
        }
      ]
    }
  ]
}
