{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib-fabric",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-fabric-5.4.1.jar",
          "url": "BoxLib-fabric-5.4.1.jar",
          "size": 209100,
          "sha512": "0bd3acd80f931db5473ac71c4a79dea420da83bd8a8059b96f93a476b4c0e973924f771e2d6c53143dbc1fb5a548b6dc031dca3fefc91e1df8e29ecb648da248",
          "sha256": "f1d07fa9725388d49691a6498a20007c06ae97ddbb1a528c432f5cba42643348",
          "sha1": "b020144cf313fd471980c96ebc62377ad35aafe6",
          "md5": "fbe817815bb41601783c4ad185735e71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "BoxLib-fabric-5.4.1.jar",
          "url": "BoxLib-fabric-5.4.1.jar",
          "size": 209100,
          "sha512": "0bd3acd80f931db5473ac71c4a79dea420da83bd8a8059b96f93a476b4c0e973924f771e2d6c53143dbc1fb5a548b6dc031dca3fefc91e1df8e29ecb648da248",
          "sha256": "f1d07fa9725388d49691a6498a20007c06ae97ddbb1a528c432f5cba42643348",
          "sha1": "b020144cf313fd471980c96ebc62377ad35aafe6",
          "md5": "fbe817815bb41601783c4ad185735e71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-fabric-5.4.1-sources.jar",
          "url": "BoxLib-fabric-5.4.1-sources.jar",
          "size": 81513,
          "sha512": "3098102df1804192bbc478b085d50619a6ad0ced019a33e926919cb520dcd67dbddd349c623132a1d71b2d150d0c2d135e78e5f76f8fe8ca605f4d905cc52d90",
          "sha256": "e9a0b9c79759d0bd3f37bc572227a4b1291c93e4fd20462c9bfab946461509fa",
          "sha1": "7990b91a0b28a3a490de93d0b44ff5e9ca6c6436",
          "md5": "729c7093b247d721a47f5228e2903f46"
        }
      ]
    }
  ]
}
