{
  "formatVersion": "1.1",
  "component": {
    "group": "me.boxadactle",
    "module": "BoxLib-Fabric",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BoxLib-Fabric-4.1.0.jar",
          "url": "BoxLib-Fabric-4.1.0.jar",
          "size": 115818,
          "sha512": "354045a862bf5d3adf33d6ae2b5d3728be2a10106bd0f9429945d1f95fbc3c5dc93402c05b284629bb9f07e489c032f710b124fd78a2fa9b3be7a88de162c1f9",
          "sha256": "05c7f2b2d05e448fa38f7b2fc81f0913beb13585c45b2433e7fa77a0a3ebc8ec",
          "sha1": "03bb26d47a500ef28d000ce6385572795f07ce2c",
          "md5": "2cb4c29536e2d3483d000c49ba86d607"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.85.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-Fabric-4.1.0.jar",
          "url": "BoxLib-Fabric-4.1.0.jar",
          "size": 115818,
          "sha512": "354045a862bf5d3adf33d6ae2b5d3728be2a10106bd0f9429945d1f95fbc3c5dc93402c05b284629bb9f07e489c032f710b124fd78a2fa9b3be7a88de162c1f9",
          "sha256": "05c7f2b2d05e448fa38f7b2fc81f0913beb13585c45b2433e7fa77a0a3ebc8ec",
          "sha1": "03bb26d47a500ef28d000ce6385572795f07ce2c",
          "md5": "2cb4c29536e2d3483d000c49ba86d607"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-Fabric-4.1.0-sources.jar",
          "url": "BoxLib-Fabric-4.1.0-sources.jar",
          "size": 75735,
          "sha512": "bae2e6f641a4c66b870d95dc118617df5b50003018de629db39348c512805f48aba62430d432744a1760d9f0e344bffa9bfd4a0034952838260bf0017cdeb39b",
          "sha256": "8ac6fac07563e8fffa133453764f516495ff3ec0c46792d60da0e25fbda11769",
          "sha1": "c56137768ee9603b2df05a4950451f2cd71ed71e",
          "md5": "4b399aec1b682e1d100f61d805edcf9b"
        }
      ]
    }
  ]
}
