{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib-forge",
    "version": "5.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BoxLib-forge-5.3.4.jar",
          "url": "BoxLib-forge-5.3.4.jar",
          "size": 189554,
          "sha512": "3596231476d63a659f0694ee5646204485ab36c84104fdbb89e66c896bd0961a21feea8f47bd6649bbf6103b90594b7704706cae19c63b6e96082b82820bbf3a",
          "sha256": "c7ed6e85d3c2e12094abadb78cc88e844e376956baae898e6a0c5c1225b5165e",
          "sha1": "8c5c2fe6264770c48c0e29af0843d436d3d9546c",
          "md5": "bb7d00190cb80339e10ea82797d2e540"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-forge-5.3.4.jar",
          "url": "BoxLib-forge-5.3.4.jar",
          "size": 189554,
          "sha512": "3596231476d63a659f0694ee5646204485ab36c84104fdbb89e66c896bd0961a21feea8f47bd6649bbf6103b90594b7704706cae19c63b6e96082b82820bbf3a",
          "sha256": "c7ed6e85d3c2e12094abadb78cc88e844e376956baae898e6a0c5c1225b5165e",
          "sha1": "8c5c2fe6264770c48c0e29af0843d436d3d9546c",
          "md5": "bb7d00190cb80339e10ea82797d2e540"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-forge-5.3.4-sources.jar",
          "url": "BoxLib-forge-5.3.4-sources.jar",
          "size": 80375,
          "sha512": "c046ddb389fb80c88d45eb103b3addb7e073bf08350ff32f1c6c488613c17d2a6a65a4762a930b7efffc4744d4694273b20bfca47d591dc6f92d4e6b8c971f4f",
          "sha256": "e463248df3b636eb09c7e2a5ed9012d3cbb3f1aea93323610d6a7ad12cf1b861",
          "sha1": "98a4ac5c3d8dae94924208a8153bba3341b5d961",
          "md5": "c1d707ce5d02a4a1377493f187fe96cc"
        }
      ]
    }
  ]
}
