{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle",
    "module": "Boxlib-forge",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Boxlib-forge-8.0.0.jar",
          "url": "Boxlib-forge-8.0.0.jar",
          "size": 164807,
          "sha512": "1aa36e35d90b1f23b87e376207b615c1caa0a664efde4fa9dfb1a00b7dbe65c467863af103f28d3fd468a33ae22b28d4a06239cd6d243997421a23c7b0a70e46",
          "sha256": "c3bf64fddcd2009fbc0ad004b459265be6c0b6fc622c969da2b1dd70447b414e",
          "sha1": "fcfbda32117f2b06a59aad10126d85b0396b8c1e",
          "md5": "f4e5a7cead31f77af1c57e0f81e607d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Boxlib-forge-8.0.0.jar",
          "url": "Boxlib-forge-8.0.0.jar",
          "size": 164807,
          "sha512": "1aa36e35d90b1f23b87e376207b615c1caa0a664efde4fa9dfb1a00b7dbe65c467863af103f28d3fd468a33ae22b28d4a06239cd6d243997421a23c7b0a70e46",
          "sha256": "c3bf64fddcd2009fbc0ad004b459265be6c0b6fc622c969da2b1dd70447b414e",
          "sha1": "fcfbda32117f2b06a59aad10126d85b0396b8c1e",
          "md5": "f4e5a7cead31f77af1c57e0f81e607d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Boxlib-forge-8.0.0-sources.jar",
          "url": "Boxlib-forge-8.0.0-sources.jar",
          "size": 101942,
          "sha512": "8519899e34b8e5d1f62914055fa9cc87977e9322896267ed08ac6ab657898ca34d991b2e41be3e58c58a33893b69f7c198e28c1ed2ed87e617f1159247645c6d",
          "sha256": "13fb51087db0582b120acf494bbca2be9a49327fb5381e7caa88b6da8683ad73",
          "sha1": "bac97018987a8d9edd9b0b6094d276442dc42f70",
          "md5": "4291970a138f7d8b269d0bcb547d84d3"
        }
      ]
    }
  ]
}
