{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib-fabric",
    "version": "5.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-fabric-5.4.2.jar",
          "url": "BoxLib-fabric-5.4.2.jar",
          "size": 209098,
          "sha512": "a247a7586a20646d91235e30b94717c6ad8e9139fd7a8532e434be7e7374665e45a982c0f9bd8350c3be38a9641b2ff0d4bb037b52cbe1984c5b5b897f7ce538",
          "sha256": "b6fcbfeb9d49b14423856ce9a2ae1e483183827445931fcbcd2167f0aac0e184",
          "sha1": "a1af63c1fe0765278f907947b27fba250e0728a9",
          "md5": "062380927b195f7129ee6d5d1067037f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "BoxLib-fabric-5.4.2.jar",
          "url": "BoxLib-fabric-5.4.2.jar",
          "size": 209098,
          "sha512": "a247a7586a20646d91235e30b94717c6ad8e9139fd7a8532e434be7e7374665e45a982c0f9bd8350c3be38a9641b2ff0d4bb037b52cbe1984c5b5b897f7ce538",
          "sha256": "b6fcbfeb9d49b14423856ce9a2ae1e483183827445931fcbcd2167f0aac0e184",
          "sha1": "a1af63c1fe0765278f907947b27fba250e0728a9",
          "md5": "062380927b195f7129ee6d5d1067037f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-fabric-5.4.2-sources.jar",
          "url": "BoxLib-fabric-5.4.2-sources.jar",
          "size": 81513,
          "sha512": "8e648db2cdce1777ee63cc7d47641a094805ffd23f10feb1807b6a51e158500e7ed5600860cd3e6179eacd70cf4241506a8426a167487a8a07dc9aac691d0602",
          "sha256": "1efb5648da4b4c97dd1233f8b6a633d38c73c1a9286a2239f18ad73e4ace3c91",
          "sha1": "899b082b3f37c9d6cd3fc51ecbe4ccb77a541834",
          "md5": "645425208f8227563cf0ccafca5ee823"
        }
      ]
    }
  ]
}
