{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle",
    "module": "Boxlib-fabric",
    "version": "10.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.89.2+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "Boxlib-fabric-10.0.0.jar",
          "url": "Boxlib-fabric-10.0.0.jar",
          "size": 197430,
          "sha512": "fd1084012f451186db94b61bd19ede4b07f336efdf717117564b7545f4ef07d8cf22281988b4a96527203cb2ae73dbe88d481cbf17ca5972f4d99b6312ba4506",
          "sha256": "fa1d0f120517d8363fb870c69ab99edb71d163b1d58d73a76a82325f94bebbfe",
          "sha1": "ad85919ffb108e0249eba590c343242876db65d7",
          "md5": "cd9e951268f23f9799c06a4b03d4461f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.89.2+1.20.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "8.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "Boxlib-fabric-10.0.0.jar",
          "url": "Boxlib-fabric-10.0.0.jar",
          "size": 197430,
          "sha512": "fd1084012f451186db94b61bd19ede4b07f336efdf717117564b7545f4ef07d8cf22281988b4a96527203cb2ae73dbe88d481cbf17ca5972f4d99b6312ba4506",
          "sha256": "fa1d0f120517d8363fb870c69ab99edb71d163b1d58d73a76a82325f94bebbfe",
          "sha1": "ad85919ffb108e0249eba590c343242876db65d7",
          "md5": "cd9e951268f23f9799c06a4b03d4461f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Boxlib-fabric-10.0.0-sources.jar",
          "url": "Boxlib-fabric-10.0.0-sources.jar",
          "size": 136185,
          "sha512": "d6dc9b7b0740cc0506efc1891bb437d001359439986c56c77c7be8d7fb0d3eb6741de57d8bd3f5e8508965ee45ff34f06887b3da433a76d0789afa83feae2646",
          "sha256": "f9c6e075080d743b5edca004bfe783fa13d1afeee951d2bd1dd3d23838280dde",
          "sha1": "28c295efa230c5e366184632e872cd76c30ce822",
          "md5": "7fd45faf1aadd44ea063f308c87e6afc"
        }
      ]
    }
  ]
}
