{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.boxadactle.boxlib",
    "module": "BoxLib-fabric",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "BoxLib-fabric-5.4.0.jar",
          "url": "BoxLib-fabric-5.4.0.jar",
          "size": 208202,
          "sha512": "e1cf9362cd07ffe09eb6223747a1acdf2514389f31f5f1528b0219bc7d103dce9662d88aa83c5449b02074b83bbde6cbf28f65bc33628625e923107b853ae91c",
          "sha256": "826810d4d77382751895ef0d8c782450f2b618fa7826017052811f7b5d6da594",
          "sha1": "36b1d837ebac777a5c0fe3409a1013b1ad0aa9c5",
          "md5": "847ce6c3a821e30b772fc6ca974ae122"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "BoxLib-fabric-5.4.0.jar",
          "url": "BoxLib-fabric-5.4.0.jar",
          "size": 208202,
          "sha512": "e1cf9362cd07ffe09eb6223747a1acdf2514389f31f5f1528b0219bc7d103dce9662d88aa83c5449b02074b83bbde6cbf28f65bc33628625e923107b853ae91c",
          "sha256": "826810d4d77382751895ef0d8c782450f2b618fa7826017052811f7b5d6da594",
          "sha1": "36b1d837ebac777a5c0fe3409a1013b1ad0aa9c5",
          "md5": "847ce6c3a821e30b772fc6ca974ae122"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BoxLib-fabric-5.4.0-sources.jar",
          "url": "BoxLib-fabric-5.4.0-sources.jar",
          "size": 81513,
          "sha512": "14ecc84f1a1c0b7543e0808c64b22f84a5daa6bb973c685e23b774ac92cdc4d26a009b32c007f5387a82d8ceb93eb0ffa8fc5eb2a247fa76e20ea9b148f1e00c",
          "sha256": "a716034d8582e9e967c74e4884907f440af7886523320d29ec5492c8a6089484",
          "sha1": "ab4f03004c2b96cdc7f8bd5e8ecde788abb69d9b",
          "md5": "291e0b75576c4f1c16a925ecfe297bb0"
        }
      ]
    }
  ]
}
